// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    // `mapPickerInline.ts` is generated by `scripts/build-map-picker-inline.js`
    // and embeds ~170 KB of third-party CSS / JS as string literals.
    // Excluding it keeps ESLint fast and avoids linting code we don't own.
    ignores: ['dist/*', 'src/components/mapPickerInline.ts'],
  },
]);
