-- =============================================================================
-- V5 — Remove Gas Selling Permit from the required seller documents.
-- =============================================================================
-- The seller is applying to obtain a Gas Selling Permit, so they cannot be
-- required to upload one before the application is approved. The permit is
-- generated by the administrator and made available to the seller once the
-- application is approved, which is already represented by the `LICENSE`
-- document type.
--
-- This migration:
--   1. Drops any existing `GAS_SELLING_PERMIT` rows so they don't break the
--      stricter check constraint or the unique (permit, document_type)
--      index on real submits.
--   2. Replaces the V4 CHECK constraint with one that no longer lists
--      `GAS_SELLING_PERMIT` as a permitted value.
-- =============================================================================

-- 1. Tidy up any historical rows that pre-date this change so the stricter
--    constraint below can be installed without constraint violations.
DELETE FROM permit_documents WHERE document_type = 'GAS_SELLING_PERMIT';

-- 2. Rebuild the `chk_permit_documents_type` CHECK constraint without the
--    `GAS_SELLING_PERMIT` value. We drop the old name first (if present on
--    the running database) and re-add it with the new set.
ALTER TABLE permit_documents DROP CONSTRAINT IF EXISTS chk_permit_documents_type;

ALTER TABLE permit_documents
    ADD CONSTRAINT chk_permit_documents_type
    CHECK (document_type IN ('APPLICATION_FORM', 'NATIONAL_ID', 'BUSINESS_LICENSE', 'PASSPORT_PHOTO', 'LICENSE'));
