package com.project.gas_delivery.permit.enums;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The PDF slots persisted under {@code permit_documents.document_type}.
 *
 * <ul>
 *   <li>{@link #APPLICATION_FORM}   – seller-completed application form
 *                                     downloaded from the system template.</li>
 *   <li>{@link #NATIONAL_ID}        – national ID card, front + back.</li>
 *   <li>{@link #BUSINESS_LICENSE}   – seller's business licence.</li>
 *   <li>{@link #PASSPORT_PHOTO}     – passport-size photograph.</li>
 *   <li>{@link #LICENSE}            – the Gas Selling Permit issued by the
 *                                     admin after approval. Available to the
 *                                     seller once the permit reaches
 *                                     {@code APPROVED}.</li>
 * </ul>
 *
 * The first four are required for submission; {@link #LICENSE} is the
 * outcome of the workflow itself — it is generated by the admin on
 * approval and is never a seller-uploaded slot.
 */
public enum PermitDocumentType {
    APPLICATION_FORM,
    NATIONAL_ID,
    BUSINESS_LICENSE,
    PASSPORT_PHOTO,
    LICENSE;

    @JsonValue
    public String toJson() {
        return name().toLowerCase();
    }

    @JsonCreator
    public static PermitDocumentType fromJson(String value) {
        if (value == null) return null;
        String normalised = value.trim().toUpperCase();
        for (PermitDocumentType t : values()) {
            if (t.name().equals(normalised)) return t;
        }
        throw new IllegalArgumentException("Unknown permit document type: " + value);
    }

    /** True for the three slots a seller must upload before submission. */
    public boolean isSellerProvided() {
        return this != LICENSE;
    }
}
